FROM php:8.2-apache
# Instalar extensiones necesarias para MySQL
RUN docker-php-ext-install pdo pdo_mysql mysqli
# Copiar tu proyecto al servidor web
COPY . /var/www/html/
# Dar permisos
RUN chown -R www-data:www-data /var/www/html
